<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MDD4All.MVVM\MDD4All.MVVM.csproj" />
        <ProjectReference Include="..\MDD4All.Notes.DataProvider.Contracts\MDD4All.Notes.DataProvider.Contracts.csproj" />
        <ProjectReference Include="..\MDD4All.Notes.DataProvider.File\MDD4All.Notes.DataProvider.File.csproj" />
        <ProjectReference Include="..\MDD4All.Notes.DataProvider.Mockup\MDD4All.Notes.DataProvider.Mockup.csproj" />
    </ItemGroup>

</Project>
