name: App Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    env:
      PROJECT_NAME: MDD4All.Notes
      APP_PROJECT_NAME: MDD4All.Notes.Apps.NoteEditorWPF

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Get version form file
      uses: pCYSl5EDgo/cat@master
      id: fileVersion
      with: 
        path: src/version.txt

    - name: Set version as environment variable
      run: echo "VERSION=$(echo $FILE_VERSION.$GITHUB_RUN_NUMBER)" >> $GITHUB_ENV
      env:
        FILE_VERSION: ${{steps.fileVersion.outputs.text}}

    - name: Echo version number
      run: echo ${{env.VERSION}}

    - name: Restore dependencies
      run: dotnet restore ./src/${{env.PROJECT_NAME}}.sln

    - name: Build
      run: dotnet build --no-restore -c Release /p:Version=${{env.VERSION}} ./src/${{env.PROJECT_NAME}}.sln

    - name: Create executable
      run: dotnet publish --configuration Release /p:Version=${{env.VERSION}} -p:PublishReadyToRun=true -p:PublishSingleFile=true --no-build --output ./Output ./src/${{env.PROJECT_NAME}}/${{env.APP_PROJECT_NAME}}.csproj

    - name: Upload artifact(s)
      uses: actions/upload-artifact@v2
      with:
        name: ${{env.PROJECT_NAME}}.${{env.VERSION}}
        path: ./Output/*.exe
      
